import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/hero";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hi Breaker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/512x512.png" />
      </Head>
      <Hero />
    </div>
  );
};

export default Home;
