import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hi Breaker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello from us 🐣</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="http://github.com/betaoverflow"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Betaoverflow
        </a>
      </footer>
    </div>
  );
};

export default Home;
