import type { NextPage } from "next";
import Head from "next/head";
import Chat from "../components/Chat";
import Flag from "../components/Flag";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Social from "../components/Social";
import Mail from "../components/Mail";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Hi Breaker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/512x512.png" />
        </Head>
        <Hero />
        <Flag />
        <Social />
        <Mail />
      </div>
      <Footer />
    </div>
  );
};

export default Home;
